import React, { useMemo, useState } from 'react';
import { AlertCircle, Camera, CheckCircle2, ChevronDown, Download, FileImage, Loader2, Plus, ScanLine, Upload, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import LiveCameraScanner from '../components/inspection/LiveCameraScanner';
import { useAuth } from '../context/auth-context';
import { downloadReportPdf, evaluateInspection, extractImages } from '../lib/api';
import { saveReport } from '../lib/reportStore';

const EMPTY = { responsible_party_name: '', responsible_party_address: '', commodity_name: '', net_quantity: '', mrp: '', consumer_care: '', consumer_phone: '', consumer_email: '', country_of_origin: '', manufacture_pack_import_date: '', best_before_or_use_by: '', unit_sale_price: '', fssai_license: '', batch_number: '', barcode: '' };
const LABELS = { responsible_party_name: 'Manufacturer / packer / importer', responsible_party_address: 'Responsible party address', commodity_name: 'Common / generic commodity name', net_quantity: 'Net quantity', mrp: 'Maximum retail price', consumer_phone: 'Consumer-care mobile number', consumer_email: 'Consumer-care email', fssai_license: 'FSSAI licence number', batch_number: 'Batch / lot number', barcode: 'Barcode / GTIN', country_of_origin: 'Country of origin', manufacture_pack_import_date: 'Manufacture / pack / import date', best_before_or_use_by: 'Best before / use by', unit_sale_price: 'Unit sale price' };

function newProduct(number) {
  return { key: `${Date.now()}-${number}`, number, details: { productId: '', productName: '' }, context: { category: 'unknown', origin: 'unknown', salesContext: 'retail' }, conditions: { date: false, perishable: false, unitPrice: false }, mode: 'upload', images: [], declarations: { ...EMPTY }, coverageComplete: false, ocrData: null, ocrLoading: false, ocrError: '', results: null, loading: false, error: '', report: null };
}

async function imageRecord(file, index, automatic = false) {
  const url = URL.createObjectURL(file); const image = new Image(); image.src = url; await image.decode().catch(() => {});
  let thumbnail = '';
  if (image.width) { const canvas = document.createElement('canvas'); const scale = Math.min(1, 420 / image.width); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); thumbnail = canvas.toDataURL('image/jpeg', .65); }
  return { id: `IMG-${String(index + 1).padStart(3, '0')}`, file, url, thumbnail, automatic, width: image.width || 0, height: image.height || 0, quality: image.width >= 800 && image.height >= 600 ? 'sufficient' : 'insufficient' };
}

function mergedOcr(current, incoming) {
  if (!current) return incoming;
  const fields = { ...(current.fields || {}) };
  Object.entries(incoming.fields || {}).forEach(([field, evidence]) => { if (!fields[field] || evidence.confidence >= fields[field].confidence) fields[field] = evidence; });
  return { ...incoming, images: [...(current.images || []), ...(incoming.images || [])].slice(-12), total_lines: (current.total_lines || 0) + (incoming.total_lines || 0), fields };
}

function refinedLines(ocrData) {
  const unique = new Map();
  (ocrData?.images || []).flatMap((image) => image.lines || []).forEach((line) => {
    const text = String(line.text || '').replace(/\s+/g, ' ').trim();
    if ((line.confidence || 0) < .6 || text.length < 2 || !/[A-Za-z0-9₹]/.test(text)) return;
    const key = text.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!key) return;
    if (!unique.has(key) || line.confidence > unique.get(key).confidence) unique.set(key, { ...line, text });
  });
  return [...unique.values()];
}

export default function NewInspectionRoute() {
  const { token } = useAuth(); const navigate = useNavigate();
  const [products, setProducts] = useState(() => [newProduct(1)]); const [activeKey, setActiveKey] = useState(() => products[0].key); const [bulkDownloading, setBulkDownloading] = useState(false);
  const active = products.find((product) => product.key === activeKey) || products[0];
  const update = (key, patch) => setProducts((current) => current.map((product) => product.key === key ? { ...product, ...(typeof patch === 'function' ? patch(product) : patch) } : product));
  const addProduct = () => { const product = newProduct(products.length + 1); setProducts((current) => [...current, product]); setActiveKey(product.key); };
  const removeProduct = (key) => { if (products.length === 1) return; products.find((p) => p.key === key)?.images.forEach((image) => URL.revokeObjectURL(image.url)); const next = products.filter((p) => p.key !== key); setProducts(next); if (activeKey === key) setActiveKey(next[0].key); };

  const runOcr = async (key, files, append = false) => {
    if (!files.length) return; update(key, { ocrLoading: true, ocrError: '' });
    try {
      const data = await extractImages(files, token); const tooBlurry = data.images?.some((image) => image.quality?.blur_status === 'high');
      update(key, (product) => {
        const ocrData = append ? mergedOcr(product.ocrData, data) : data;
        if (tooBlurry) return { ocrData, ocrError: 'Frame too blurred to update fields. Hold the package steady, fill the guide, and scan again.' };
        const declarations = { ...product.declarations };
        Object.entries(data.fields || {}).forEach(([field, evidence]) => { const previous = product.ocrData?.fields?.[field]; if (field in declarations && evidence?.value && (!append || !previous || evidence.confidence >= previous.confidence)) declarations[field] = evidence.value; });
        const detectedName = data.fields?.product_name?.value || data.fields?.commodity_name?.value;
        return { ocrData, declarations, details: { ...product.details, productName: product.details.productName || detectedName || '' }, context: data.fields?.country_of_origin?.value && !/india/i.test(data.fields.country_of_origin.value) ? { ...product.context, origin: 'imported' } : product.context, ocrError: '' };
      });
    } catch (error) { update(key, { ocrError: error.message }); } finally { update(key, { ocrLoading: false }); }
  };

  const addImages = async (event) => { const files = Array.from(event.target.files || []).slice(0, 12 - active.images.length); const records = await Promise.all(files.map((file, index) => imageRecord(file, active.images.length + index))); const next = [...active.images, ...records]; update(active.key, { images: next }); event.target.value = ''; await runOcr(active.key, next.map((item) => item.file)); };
  const cameraCapture = async (file, automatic) => { const record = await imageRecord(file, active.images.length, automatic); const stable = automatic ? active.images.filter((item) => !item.automatic) : active.images; const next = [...stable, record].slice(-12).map((item, index) => ({ ...item, id: `IMG-${String(index + 1).padStart(3, '0')}` })); update(active.key, { images: next }); await runOcr(active.key, [file], true); };
  const removeImage = (id) => { const removed = active.images.find((image) => image.id === id); if (removed) URL.revokeObjectURL(removed.url); const images = active.images.filter((image) => image.id !== id).map((image, index) => ({ ...image, id: `IMG-${String(index + 1).padStart(3, '0')}` })); update(active.key, { images, ...(images.length ? {} : { ocrData: null, declarations: { ...EMPTY } }) }); };

  const analyze = async () => {
    if (!active.images.length) { update(active.key, { error: 'Add front, back, or side photographs for this product before analysis.' }); return; }
    update(active.key, { loading: true, error: '' });
    try {
      const evidence = Object.entries(active.declarations).filter(([, value]) => value.trim()).map(([field, value]) => { const detected = active.ocrData?.fields?.[field]; return { field, value: value.trim(), confidence: detected?.value === value.trim() ? detected.confidence : .95, source_type: detected?.value === value.trim() ? 'ocr' : 'inspector_entered', image_id: detected?.image_id || active.images[0].id, bbox: detected?.bbox || null }; });
      const response = await evaluateInspection({ context: { inspection_mode: 'physical_package', package_context: active.context.salesContext === 'wholesale' ? 'wholesale' : active.context.salesContext === 'unknown' ? 'unknown' : 'retail_prepackaged', product_category: active.context.category, origin: active.context.origin, sales_context: active.context.salesContext, product_conditions: [active.conditions.date && 'date_declaration_required', active.conditions.perishable && 'may_become_unfit_for_human_consumption', active.conditions.unitPrice && 'unit_sale_price_required'].filter(Boolean), inspection_date: new Date().toISOString().slice(0, 10) }, evidence, field_coverage: Object.keys(active.declarations).reduce((result, field) => ({ ...result, [field]: active.coverageComplete ? 'complete' : 'incomplete' }), {}), image_quality: active.images.map((image) => ({ image_id: image.id, status: image.quality })) }, token);
      const applicable = response.results.filter((item) => item.outcome !== 'NOT_APPLICABLE'); const pass = applicable.filter((item) => item.outcome === 'PASS').length; const score = applicable.length ? Math.round(pass / applicable.length * 100) : 0; const status = response.counts.FAIL ? 'NON_COMPLIANT' : response.counts.REVIEW ? 'REVIEW' : 'COMPLIANT'; const id = `PMX-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}-${Date.now().toString().slice(-5)}-P${active.number}`; const ocrLines = refinedLines(active.ocrData);
      const report = { id, batchId: `BATCH-${products[0].key.split('-')[0]}`, date: new Date().toLocaleString('en-IN'), status, score, details: { productId: active.details.productId || active.declarations.barcode || id, productName: active.details.productName || active.declarations.commodity_name || 'Unnamed package', category: active.context.category, origin: active.context.origin, salesContext: active.context.salesContext }, declarations: active.declarations, counts: response.counts, results: response.results, violations: applicable.filter((item) => ['FAIL', 'REVIEW'].includes(item.outcome)), ocrLines, ocrStatus: ocrLines.length ? 'PASS — text detected' : 'FAIL — no text detected', imageCount: active.images.length, imageQuality: active.images.map(({ id: imageId, width, height, quality }) => ({ imageId, width, height, quality })), thumbnail: active.images[0]?.thumbnail || '' };
      saveReport(report); update(active.key, { results: response, report }); setTimeout(() => document.getElementById('analysis-results')?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch (error) { update(active.key, { error: error.message }); } finally { update(active.key, { loading: false }); }
  };

  const completed = products.map((product) => product.report).filter(Boolean);
  const downloadBulk = async () => { if (!completed.length) return; setBulkDownloading(true); try { const blob = await downloadReportPdf({ id: `BATCH-${products[0].key.split('-')[0]}`, reports: completed }, token); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `PackMetrix-bulk-${Date.now()}.pdf`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } finally { setBulkDownloading(false); } };
  const quality = useMemo(() => active.images.length ? `${active.images.filter((image) => image.quality === 'sufficient').length}/${active.images.length} panels meet the resolution screen` : 'No evidence panels for this product', [active.images]);
  const visible = active.results?.results?.filter((item) => item.outcome !== 'NOT_APPLICABLE') || [];
  const actions = completed.length ? <button onClick={downloadBulk} disabled={bulkDownloading} className="flex items-center gap-2 bg-slate-950 text-white px-4 py-2.5 rounded-xl text-sm font-bold"><Download className="w-4 h-4" />{bulkDownloading ? 'Building…' : `Bulk report (${completed.length})`}</button> : null;

  return <AppShell title="Batch product inspection" eyebrow="MULTI-PRODUCT AI SCAN" actions={actions}><div className="space-y-6">
    <section className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm"><div className="flex flex-wrap gap-2 items-center"><span className="text-xs font-bold text-slate-500 mr-2">PRODUCT GROUPS</span>{products.map((product) => <button key={product.key} onClick={() => setActiveKey(product.key)} className={`group flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold border ${product.key === active.key ? 'bg-sky-50 text-sky-800 border-sky-300' : 'bg-white text-slate-600 border-slate-200'}`}><span>{product.details.productName || `Product ${product.number}`}</span><span className={`w-2 h-2 rounded-full ${product.report ? 'bg-emerald-500' : product.images.length ? 'bg-amber-500' : 'bg-slate-300'}`} />{products.length > 1 && <span onClick={(event) => { event.stopPropagation(); removeProduct(product.key); }} className="opacity-40 group-hover:opacity-100"><X className="w-3.5 h-3.5" /></span>}</button>)}<button onClick={addProduct} className="flex items-center gap-1.5 px-3 py-2 rounded-xl border border-dashed border-sky-300 text-sky-700 text-sm font-bold"><Plus className="w-4 h-4" />Add product</button></div><p className="text-xs text-slate-500 mt-3">Keep every product’s front, back, and side panels inside its own tab. The system never merges text across product groups.</p></section>

    <Section number="1" title={`Identify Product ${active.number}`} subtitle="The name and barcode may be auto-filled from this product’s images."><div className="grid sm:grid-cols-2 gap-4"><Text label="Product ID / barcode" value={active.details.productId} onChange={(value) => update(active.key, { details: { ...active.details, productId: value } })} placeholder="Auto-filled or enter identifier" /><Text label="Product name" value={active.details.productName} onChange={(value) => update(active.key, { details: { ...active.details, productName: value } })} placeholder="e.g. Yellow Chips / Chocolate Desire" /></div><details className="mt-5 group"><summary className="cursor-pointer flex items-center gap-2 text-sm font-bold text-slate-600"><ChevronDown className="w-4 h-4 group-open:rotate-180" />Advanced legal applicability</summary><p className="text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded-xl p-3 mt-3">Unknown facts remain REVIEW; the image alone cannot prove sales channel or every exception.</p><div className="grid sm:grid-cols-3 gap-4 mt-4"><Select label="Category" value={active.context.category} onChange={(value) => update(active.key, { context: { ...active.context, category: value } })} options={[['unknown','Auto / unknown'],['food','Food'],['beverage','Beverage'],['personal_care','Personal care'],['household','Household'],['other','Other']]} /><Select label="Origin" value={active.context.origin} onChange={(value) => update(active.key, { context: { ...active.context, origin: value } })} options={[['unknown','Auto / unknown'],['domestic','Manufactured in India'],['imported','Imported']]} /><Select label="Sales context" value={active.context.salesContext} onChange={(value) => update(active.key, { context: { ...active.context, salesContext: value } })} options={[['retail','Retail package'],['ecommerce','E-commerce'],['wholesale','Wholesale'],['unknown','Unknown']]} /></div><div className="mt-4 flex flex-wrap gap-4">{[['date','Date declaration applies'],['perishable','May become unfit for consumption'],['unitPrice','Unit sale price applies']].map(([key,label]) => <label key={key} className="text-sm flex gap-2"><input type="checkbox" checked={active.conditions[key]} onChange={(event) => update(active.key, { conditions: { ...active.conditions, [key]: event.target.checked } })} />{label}</label>)}</div></details></Section>

    <Section number="2" title={`Capture panels for Product ${active.number}`} subtitle="Add only this product’s front, back, side, lid, or bottom images."><div className="inline-flex bg-slate-100 rounded-xl p-1"><button onClick={() => update(active.key, { mode: 'upload' })} className={`px-4 py-2 rounded-lg text-sm font-bold flex gap-2 ${active.mode === 'upload' ? 'bg-white shadow text-sky-700' : 'text-slate-500'}`}><Upload className="w-4 h-4" />Upload</button><button onClick={() => update(active.key, { mode: 'camera' })} className={`px-4 py-2 rounded-lg text-sm font-bold flex gap-2 ${active.mode === 'camera' ? 'bg-white shadow text-sky-700' : 'text-slate-500'}`}><Camera className="w-4 h-4" />Live camera</button></div>{active.mode === 'upload' ? <label className={`mt-4 min-h-36 border-2 border-dashed rounded-2xl grid place-items-center text-center cursor-pointer ${active.ocrLoading ? 'opacity-60 pointer-events-none' : 'border-slate-300 hover:border-sky-400 bg-slate-50'}`}><div>{active.ocrLoading ? <Loader2 className="w-7 h-7 mx-auto animate-spin text-sky-700" /> : <Upload className="w-7 h-7 mx-auto text-sky-700" />}<p className="font-bold text-sm mt-2">{active.ocrLoading ? 'Orienting and mapping label text…' : 'Add front, back and side photographs'}</p><p className="text-xs text-slate-500 mt-1">Up to 12 panels for Product {active.number}</p></div><input type="file" accept="image/*" multiple onChange={addImages} className="hidden" /></label> : <div className="mt-4"><LiveCameraScanner onCapture={cameraCapture} ocrData={active.ocrData} busy={active.ocrLoading} /></div>}{active.images.length > 0 && <div className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-6 gap-3 mt-5">{active.images.map((image) => <div key={image.id} className="border border-slate-200 rounded-xl overflow-hidden relative"><img src={image.url} alt={image.file.name} className="w-full h-24 object-cover" /><button onClick={() => removeImage(image.id)} className="absolute top-1.5 right-1.5 bg-slate-950/80 text-white p-1 rounded-full"><X className="w-3 h-3" /></button><div className="p-2 text-[10px]"><b className="font-mono">{image.id}</b><p className="truncate text-slate-500">{image.file.name}</p></div></div>)}</div>}<p className="mt-4 text-xs text-slate-500 flex gap-2"><FileImage className="w-4 h-4" />{quality}</p>{active.ocrError && <p className="mt-3 text-sm text-rose-700 bg-rose-50 border border-rose-200 rounded-xl p-3">{active.ocrError}</p>}</Section>

    <Section number="3" title="Review mapped declarations" subtitle="Only field-specific normalized values are inserted; all other OCR remains in the transcript."><div className="grid md:grid-cols-2 gap-4">{Object.entries(LABELS).map(([field,label]) => <Text key={field} label={label} value={active.declarations[field]} onChange={(value) => update(active.key, { declarations: { ...active.declarations, [field]: value } })} placeholder="Not reliably detected" />)}</div><label className="mt-5 flex gap-3 bg-amber-50 border border-amber-200 rounded-xl p-4"><input type="checkbox" checked={active.coverageComplete} onChange={(event) => update(active.key, { coverageComplete: event.target.checked })} /><span><b className="text-sm">All relevant panels for Product {active.number} are visible</b><p className="text-xs text-amber-800 mt-1">Otherwise missing declarations remain REVIEW instead of being treated as absent.</p></span></label></Section>

    {active.error && <div className="bg-rose-50 border border-rose-200 rounded-xl p-4 text-sm text-rose-800 flex gap-2"><AlertCircle className="w-5 h-5" />{active.error}</div>}<button onClick={analyze} disabled={active.loading || active.ocrLoading} className="w-full bg-slate-950 hover:bg-sky-800 text-white rounded-2xl py-4 font-black flex justify-center gap-2 disabled:opacity-50">{active.loading ? <Loader2 className="animate-spin" /> : <ScanLine />}Analyze Product {active.number}</button>
    {active.results && <section id="analysis-results" className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-xs font-bold text-sky-700 tracking-widest">PRODUCT {active.number} COMPLETE</p><h2 className="text-2xl font-black mt-1">Rule-by-rule findings</h2></div><button onClick={() => navigate(`/reports/${active.report?.id}`)} className="text-sm font-bold text-sky-700">Open report →</button></div><div className="grid grid-cols-3 gap-3 mt-5">{[['PASS',active.results.counts.PASS,'text-emerald-700 bg-emerald-50'],['FAIL',active.results.counts.FAIL,'text-rose-700 bg-rose-50'],['REVIEW',active.results.counts.REVIEW,'text-amber-700 bg-amber-50']].map(([label,value,color]) => <div key={label} className={`rounded-xl p-4 ${color}`}><p className="text-2xl font-black">{value}</p><p className="text-xs font-bold">{label}</p></div>)}</div><div className="mt-5 divide-y divide-slate-100">{visible.map((item) => <div key={item.rule_id} className="py-4 flex gap-3">{item.outcome === 'PASS' ? <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" /> : <AlertCircle className={`w-5 h-5 shrink-0 ${item.outcome === 'FAIL' ? 'text-rose-600' : 'text-amber-600'}`} />}<div><p className="font-bold text-sm">{item.rule_reference} · {item.outcome}</p><p className="text-sm text-slate-600 mt-1">{item.reason}</p></div></div>)}</div></section>}
  </div></AppShell>;
}

function Section({ number, title, subtitle, children }) { return <section className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm"><div className="flex items-center gap-3 mb-5"><span className="w-9 h-9 rounded-full bg-slate-950 text-white grid place-items-center font-black shrink-0">{number}</span><div><h2 className="font-black text-lg">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div></div>{children}</section>; }
function Text({ label, value, onChange, placeholder }) { return <label><span className="text-xs font-bold uppercase text-slate-600">{label}</span><input value={value || ''} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-sky-500 focus:ring-2 focus:ring-sky-100" /></label>; }
function Select({ label, value, onChange, options }) { return <label><span className="text-xs font-bold uppercase text-slate-600">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm bg-white">{options.map(([option,labelText]) => <option key={option} value={option}>{labelText}</option>)}</select></label>; }
