import React, { useMemo, useState } from 'react';
import { ChevronDown, History, PackageSearch } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { getReports } from '../lib/reportStore';

export default function ProductsRoute() {
  const navigate = useNavigate(); const [open, setOpen] = useState('');
  const products = useMemo(() => {
    const groups = new Map();
    getReports().filter((r) => !r.archived).forEach((report) => { const key = report.declarations?.barcode || report.details?.productId || report.details?.productName || report.id; const group = groups.get(key) || []; group.push(report); groups.set(key, group); });
    return [...groups.entries()].map(([key, history]) => ({ key, history, latest: history[0] }));
  }, []);
  return <AppShell title="Product register" eyebrow="PRODUCT LISTINGS"><div className="space-y-4">{products.map(({ key, latest, history }) => <section key={key} className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><button onClick={() => setOpen(open === key ? '' : key)} className="w-full text-left p-5 flex items-center gap-4"><div className="w-11 h-11 bg-sky-50 text-sky-700 rounded-xl grid place-items-center"><PackageSearch /></div><div className="min-w-0"><p className="font-black">{latest.details?.productName || latest.declarations?.commodity_name || 'Unnamed product'}</p><p className="text-xs font-mono text-slate-500">{latest.declarations?.barcode || latest.details?.productId || 'GTIN not detected'}</p></div><div className="ml-auto text-right hidden sm:block"><p className="text-sm font-semibold">{latest.declarations?.responsible_party_name || 'Manufacturer not detected'}</p><p className="text-xs text-slate-500 mt-1">{latest.workflowStatus === 'RESOLVED' ? 'Officer verified' : latest.status === 'REVIEW' ? 'Needs review' : latest.status} · {latest.date} · {history.length} inspection{history.length === 1 ? '' : 's'}</p></div><ChevronDown className={`w-5 h-5 text-slate-400 transition ${open === key ? 'rotate-180' : ''}`} /></button>{open === key && <div className="border-t border-slate-100 p-5 bg-slate-50"><h3 className="text-xs font-bold uppercase text-slate-500 flex gap-2"><History className="w-4 h-4" />Inspection history</h3><div className="mt-3 space-y-2">{history.map((report) => <button key={report.id} onClick={() => navigate(`/reports/${report.id}`)} className="w-full bg-white border border-slate-200 rounded-xl p-3 flex items-center text-left"><div><p className="text-sm font-bold">{report.id}</p><p className="text-xs text-slate-500">{report.date}</p></div><span className="ml-auto text-xs font-bold">{report.workflowStatus === 'RESOLVED' ? 'OFFICER VERIFIED' : report.status === 'REVIEW' ? 'NEEDS REVIEW' : report.status}</span></button>)}</div></div>}</section>)}{!products.length && <div className="bg-white border border-slate-200 rounded-2xl p-16 text-center"><PackageSearch className="mx-auto text-slate-400 w-10 h-10" /><p className="font-bold mt-3">No products listed yet</p><p className="text-sm text-slate-500 mt-1">A listing is created after the first completed scan.</p></div>}</div></AppShell>;
}
