import React, { useMemo, useState } from 'react';
import { Download, Eye, FileSearch, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { getReports } from '../lib/reportStore';

export default function ReportsRoute() {
  const navigate = useNavigate();
  const reports = useMemo(() => getReports(), []);
  const [query, setQuery] = useState('');
  const filtered = reports.filter((r) => JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
  return <AppShell title="Inspection reports" eyebrow="REPORT REGISTER"><div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center gap-4"><div><h2 className="text-xl font-black">Completed analyses</h2><p className="text-sm text-slate-500">Open evidence, violations, OCR transcript, or download the signed-session PDF.</p></div><label className="sm:ml-auto flex items-center gap-2 border border-slate-200 rounded-xl px-3 py-2"><Search className="w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search product or ID" className="outline-none text-sm" /></label></div>{!filtered.length ? <div className="p-16 text-center"><FileSearch className="w-10 h-10 text-slate-400 mx-auto" /><h3 className="font-bold mt-4">No matching reports</h3><p className="text-sm text-slate-500 mt-1">Completed product inspections appear here.</p></div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-xs uppercase"><tr><th className="text-left p-4">Product / report</th><th className="text-left p-4">Manufacturer</th><th className="text-left p-4">Assessment</th><th className="text-left p-4">Score</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((r) => <tr key={r.id}><td className="p-4"><p className="font-bold">{r.details?.productName || 'Unnamed product'}</p><p className="text-xs font-mono text-slate-500 mt-1">{r.id} · {r.date}</p></td><td className="p-4 text-slate-600 max-w-xs truncate">{r.declarations?.responsible_party_name || 'Not detected'}</td><td className="p-4"><span className={`text-[10px] font-bold px-2 py-1 rounded-full ${r.status === 'COMPLIANT' ? 'bg-emerald-50 text-emerald-700' : r.status === 'NON_COMPLIANT' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{r.status}</span></td><td className="p-4 font-black">{r.score}%</td><td className="p-4"><button onClick={() => navigate(`/reports/${r.id}`)} className="mx-auto flex items-center gap-2 text-sky-700 font-bold"><Eye className="w-4 h-4" />View <Download className="w-3.5 h-3.5" /></button></td></tr>)}</tbody></table></div>}</div></AppShell>;
}
