import React, { useState } from 'react';
import { AlertTriangle, Archive, ArrowLeft, CheckCircle2, Download, FileText, Image as ImageIcon, RotateCcw, Save } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { useAuth } from '../context/auth-context';
import { downloadReportPdf } from '../lib/api';
import { archiveReport, getBulkBatch, getReport, updateReport } from '../lib/reportStore';

const DETAIL_FIELDS = [['Brand name','brand_name'],['Manufacturer / packer / importer','responsible_party_name'],['Responsible-party address','responsible_party_address'],['Common / generic commodity','commodity_name'],['Net quantity','net_quantity'],['Maximum retail price','mrp'],['FSSAI licence','fssai_license'],['Batch / lot','batch_number'],['Manufacture / pack date','manufacture_pack_import_date'],['Use by / best before','best_before_or_use_by'],['Unit sale price','unit_sale_price'],['Country of origin','country_of_origin'],['Consumer mobile','consumer_phone'],['Consumer email','consumer_email'],['Barcode / GTIN','barcode']];
const OUTCOMES = [['COMPLIANT','Confirm compliant'],['VIOLATION','Confirm violation'],['MORE_EVIDENCE','Needs more evidence']];

export default function ReportDetailRoute() {
  const { id } = useParams(); const navigate = useNavigate(); const { token, user } = useAuth();
  const [report, setReport] = useState(() => getReport(id)); const [downloading, setDownloading] = useState(false); const [error, setError] = useState('');
  if (!report) return <AppShell title="Report not found"><div className="bg-white rounded-2xl border p-12 text-center"><p className="font-bold">This report is not available in this browser workspace.</p><button onClick={() => navigate('/reports')} className="mt-4 text-sky-700 font-bold">Back to reports</button></div></AppShell>;
  const save = (patch) => { const next = updateReport(report.id, patch); setReport(next); return next; };
  const download = async () => { setDownloading(true); setError(''); try { const blob = await downloadReportPdf(report, token); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `PackMetrix-${report.id}.pdf`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (failure) { setError(failure.message); } finally { setDownloading(false); } };
  const resolveFinding = (ruleId, patch) => save({ results: report.results.map((item) => item.rule_id === ruleId ? { ...item, ...patch } : item), violations: report.violations.map((item) => item.rule_id === ruleId ? { ...item, ...patch } : item) });
  const finalise = () => { const unresolved = report.results.filter((item) => item.outcome === 'REVIEW' && !item.resolvedOutcome).length; save({ workflowStatus: 'RESOLVED', finalDecision: unresolved ? 'Resolved with additional evidence required' : 'Officer review completed', reviewedBy: { id: user?.id, name: user?.name, email: user?.email }, reviewedAt: new Date().toLocaleString('en-IN') }); };
  const archive = () => { if (!window.confirm(`Archive report ${report.id}? It can be restored from the report register.`)) return; archiveReport(report.id); navigate('/reports'); };
  const action = <div className="flex gap-2"><button onClick={download} disabled={downloading} className="flex items-center gap-2 bg-slate-950 text-white rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-50"><Download className="w-4 h-4" />{downloading ? 'Generating…' : 'Download PDF'}</button></div>;
  const statusLabel = report.workflowStatus === 'RESOLVED' ? 'OFFICER VERIFIED / RESOLVED' : report.status === 'REVIEW' ? 'REVIEW REQUIRED' : report.status === 'NON_COMPLIANT' ? 'POTENTIAL ISSUE' : 'PASS';
  const bulkBatch = report.batchId ? getBulkBatch(report.batchId) : null; const failures = (report.results || []).filter((item) => item.outcome === 'FAIL'); const reviews = (report.results || []).filter((item) => item.outcome === 'REVIEW');
  return <AppShell title={`Report ${report.id}`} eyebrow="AI COMPLIANCE ANALYSIS" actions={action}>
    <button onClick={() => navigate(bulkBatch ? `/inspections/new?mode=bulk&batch=${encodeURIComponent(report.batchId)}` : '/reports')} className="flex gap-2 items-center text-sm font-bold text-slate-600 mb-5"><ArrowLeft className="w-4 h-4" />{bulkBatch ? 'Back to bulk results' : 'All reports'}</button>
    {error && <div className="mb-5 bg-rose-50 border border-rose-200 rounded-xl p-4 text-sm text-rose-800">{error}</div>}
    <section className="grid xl:grid-cols-[.7fr_1.3fr] gap-5">
      <div className="space-y-5"><div className="bg-slate-950 text-white rounded-2xl p-6"><p className="text-xs font-bold text-sky-400 tracking-widest">ASSESSMENT</p><p className="text-3xl font-black mt-3">{statusLabel}</p><div className="grid grid-cols-3 gap-2 mt-5 text-center"><Count value={report.counts?.PASS} label="Passed" /><Count value={report.counts?.FAIL} label="Potential" /><Count value={report.counts?.REVIEW} label="Verify" /></div><p className="text-xs text-slate-300 leading-5 mt-5">{report.overallReason || (failures.length ? 'At least one applicable check failed with sufficient evidence.' : reviews.length ? 'No confirmed failure was found; one or more checks still need verification.' : 'All applicable checks passed.')}</p><p className="text-xs text-slate-400 leading-5 mt-2">Evidence verification: {report.verificationScore ?? report.score ?? 0}% complete. This is not a legal compliance percentage; REVIEW is not final non-compliance.</p></div><Card title="Submitted evidence" icon={ImageIcon}>{report.thumbnail ? <img src={report.thumbnail} className="w-full rounded-xl max-h-72 object-contain bg-slate-100" alt="Submitted package evidence" /> : <p className="text-sm text-slate-500">Preview not retained.</p>}<p className="mt-4 text-xs text-slate-500">{report.imageCount} package surface(s) · {report.ocrStatus}</p></Card><Card title={`Complete extracted text (${report.ocrLines?.length || 0})`} icon={FileText}>{report.ocrLines?.length ? <div className="max-h-80 overflow-y-auto space-y-2">{report.ocrLines.map((line, index) => <div key={`${line.text}-${index}`} className="grid grid-cols-[28px_1fr_auto] gap-2 text-xs border-b border-slate-100 pb-2"><span className="font-mono text-slate-400">{String(index + 1).padStart(2, '0')}</span><span className="break-words">{line.text}</span><span className="text-emerald-700 font-bold">{Math.round((line.confidence || 0) * 100)}%</span></div>)}</div> : <p className="text-sm text-slate-500">No OCR transcript was retained for this report.</p>}</Card><Card title="Ingredients" icon={FileText}><p className="text-sm leading-6">{report.declarations?.ingredients || 'Not reliably detected'}</p></Card><Card title="Nutrition information" icon={FileText}><p className="text-sm leading-6">{report.declarations?.nutrition_information || 'Not reliably detected'}</p></Card></div>
      <div className="space-y-5"><Card title="Product and declaration details" icon={FileText}><Info label="Product ID" value={report.details?.productId || report.id} /><Info label="Product name" value={report.details?.productName} />{DETAIL_FIELDS.map(([label, field]) => <Info key={field} label={label} value={report.declarations?.[field]} evidence={report.fieldEvidence?.[field]} />)}</Card>{failures.length > 0 && <Card title={`Potential issues (${failures.length})`} icon={AlertTriangle}><div className="space-y-4">{failures.map((item) => <Finding key={item.rule_id} item={item} onChange={(patch) => resolveFinding(item.rule_id, patch)} />)}</div></Card>}<Card title={`Needs verification (${reviews.length})`} icon={AlertTriangle}>{reviews.length ? <div className="space-y-4">{reviews.map((item) => <Finding key={item.rule_id} item={item} onChange={(patch) => resolveFinding(item.rule_id, patch)} />)}</div> : <p className="flex gap-2 text-sm text-emerald-700"><CheckCircle2 className="w-5 h-5" />No unresolved review findings.</p>}</Card><Card title="Officer resolution" icon={Save}><label className="text-xs font-bold uppercase text-slate-600">Final officer remarks<textarea value={report.officerRemarks || ''} onChange={(e) => save({ officerRemarks: e.target.value })} rows="3" className="mt-2 w-full border border-slate-300 rounded-xl p-3 text-sm normal-case font-normal" placeholder="Record the basis for the final disposition" /></label><div className="flex flex-wrap gap-2 mt-4">{report.workflowStatus !== 'RESOLVED' ? <button onClick={finalise} className="bg-sky-700 text-white rounded-xl px-4 py-2.5 text-sm font-bold">Mark resolved</button> : <button onClick={() => save({ workflowStatus: 'OPEN', finalDecision: 'Reopened for officer review' })} className="flex gap-2 items-center border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold"><RotateCcw className="w-4 h-4" />Reopen</button>}<button onClick={archive} className="flex gap-2 items-center border border-rose-200 text-rose-700 rounded-xl px-4 py-2.5 text-sm font-bold"><Archive className="w-4 h-4" />Archive report</button></div>{report.reviewedAt && <p className="text-xs text-slate-500 mt-4">Last resolved by {report.reviewedBy?.name || 'authorized officer'} on {report.reviewedAt}</p>}</Card></div>
    </section>
  </AppShell>;
}

function Finding({ item, onChange }) { return <div className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-sm">{item.requirement} — {item.resolvedOutcome ? 'Officer Verified' : item.outcome === 'FAIL' ? 'Potential Issue' : 'Review Required'}</p>{item.evidence?.length > 0 && <p className="text-xs text-slate-500 mt-2"><b>Detected:</b> {item.evidence.map((e) => e.value).join('; ')}</p>}<p className="text-sm text-slate-600 mt-2"><b>Reason:</b> {item.reason}</p><p className="text-xs text-slate-400 mt-1">Legal reference: {item.rule_reference}</p><div className="flex flex-wrap gap-2 mt-3">{OUTCOMES.map(([value,label]) => <button key={value} onClick={() => onChange({ resolvedOutcome: value })} className={`rounded-lg border px-3 py-1.5 text-xs font-bold ${item.resolvedOutcome === value ? 'bg-sky-50 border-sky-400 text-sky-800' : 'border-slate-200 text-slate-600'}`}>{label}</button>)}</div><textarea value={item.officerRemark || ''} onChange={(e) => onChange({ officerRemark: e.target.value })} placeholder="Add officer remark" rows="2" className="mt-3 w-full rounded-lg border border-slate-200 p-2.5 text-sm" /><button onClick={() => onChange({ decisionSavedAt: new Date().toLocaleString('en-IN') })} className="mt-2 text-xs font-bold text-sky-700">Save final decision</button>{item.decisionSavedAt && <span className="ml-3 text-xs text-emerald-700">Saved {item.decisionSavedAt}</span>}</div>; }
function Card({ title, icon: Icon, children }) { return <section className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><h3 className="font-black flex items-center gap-2"><Icon className="w-4 h-4 text-sky-700" />{title}</h3><div className="mt-4">{children}</div></section>; }
function Count({ value = 0, label }) { return <div className="rounded-lg bg-white/5 p-2"><p className="text-xl font-black">{value}</p><p className="text-[10px] text-slate-400">{label}</p></div>; }
function Info({ label, value, evidence }) { const uncertain = evidence && evidence.confidence < .8; const matchedEvidence = value && evidence?.value === value; return <div className="grid sm:grid-cols-[210px_1fr] gap-1 py-2 border-b border-slate-100 last:border-0"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="text-sm font-semibold break-words">{value || 'Not reliably detected'}{matchedEvidence && <span className={`ml-2 text-[10px] rounded-full px-2 py-0.5 ${uncertain ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'}`}>{uncertain ? 'Review' : 'AI extracted'} {Math.round(evidence.confidence * 100)}%</span>}</p></div>; }
