import React, { useState } from 'react';
import { ArchiveRestore, Eye, FileSearch, Search } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { getReports, restoreReport } from '../lib/reportStore';

export default function ReportsRoute() {
  const navigate = useNavigate();
  const reports = getReports();
  const [query, setQuery] = useState(''); const [showArchived, setShowArchived] = useState(false); const [, refresh] = useState(0);
  const filtered = reports.filter((r) => Boolean(r.archived) === showArchived && JSON.stringify(r).toLowerCase().includes(query.toLowerCase()));
  return <AppShell title="Inspection reports" eyebrow="REPORT REGISTER"><div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-200 flex flex-col sm:flex-row sm:items-center gap-4"><div><h2 className="text-xl font-black">{showArchived ? 'Archived reports' : 'Inspection reports'}</h2><p className="text-sm text-slate-500">Review evidence, officer decisions, report status, and professional PDF output.</p></div><button onClick={() => setShowArchived(!showArchived)} className="sm:ml-auto text-sm font-bold text-slate-600">{showArchived ? 'Show active' : 'Show archived'}</button><label className="flex items-center gap-2 border border-slate-200 rounded-xl px-3 py-2"><Search className="w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search product or ID" className="outline-none text-sm" /></label></div>{!filtered.length ? <div className="p-16 text-center"><FileSearch className="w-10 h-10 text-slate-400 mx-auto" /><h3 className="font-bold mt-4">No matching reports</h3><p className="text-sm text-slate-500 mt-1">{showArchived ? 'Archived reports appear here.' : 'Completed product inspections appear here.'}</p></div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-xs uppercase"><tr><th className="text-left p-4">Product / report</th><th className="text-left p-4">Manufacturer</th><th className="text-left p-4">Assessment</th><th className="text-left p-4">Verification</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((r) => <tr key={r.id}><td className="p-4"><p className="font-bold">{r.details?.productName || 'Unnamed product'}</p><p className="text-xs font-mono text-slate-500 mt-1">{r.id} · {r.date}</p></td><td className="p-4 text-slate-600 max-w-xs truncate">{r.declarations?.responsible_party_name || 'Not detected'}</td><td className="p-4"><span className={`text-[10px] font-bold px-2 py-1 rounded-full ${r.workflowStatus === 'RESOLVED' ? 'bg-sky-50 text-sky-700' : r.status === 'COMPLIANT' ? 'bg-emerald-50 text-emerald-700' : r.status === 'NON_COMPLIANT' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{r.workflowStatus === 'RESOLVED' ? 'OFFICER VERIFIED' : r.status === 'REVIEW' ? 'NEEDS REVIEW' : r.status}</span></td><td className="p-4 font-black">{r.verificationScore ?? r.score}%</td><td className="p-4">{showArchived ? <button onClick={() => { restoreReport(r.id); refresh((x) => x + 1); }} className="mx-auto flex items-center gap-2 text-sky-700 font-bold"><ArchiveRestore className="w-4 h-4" />Restore</button> : <button onClick={() => navigate(`/reports/${r.id}`)} className="mx-auto flex items-center gap-2 text-sky-700 font-bold"><Eye className="w-4 h-4" />View</button>}</td></tr>)}</tbody></table></div>}</div></AppShell>;
}
