import React, { useState } from 'react';
import { AlertTriangle, Archive, ArrowLeft, CheckCircle2, Download, FileText, HelpCircle, Image as ImageIcon, RotateCcw, Save, XCircle } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { useAuth } from '../context/auth-context';
import { downloadReportPdf } from '../lib/api';
import { archiveReport, getBulkBatch, getReport, updateReport } from '../lib/reportStore';

const DETAIL_FIELDS = [['Brand name','brand_name'],['Manufacturer / packer / importer','responsible_party_name'],['Responsible-party address','responsible_party_address'],['Common / generic commodity','commodity_name'],['Net quantity','net_quantity'],['Maximum retail price','mrp'],['FSSAI licence','fssai_license'],['Batch / lot','batch_number'],['Manufacture / pack date','manufacture_pack_import_date'],['Use by / best before','best_before_or_use_by'],['Unit sale price','unit_sale_price'],['Country of origin','country_of_origin'],['Consumer mobile','consumer_phone'],['Consumer email','consumer_email'],['Barcode / GTIN','barcode']];
const OUTCOMES = [['COMPLIANT','Confirm compliant'],['VIOLATION','Confirm violation'],['MORE_EVIDENCE','Needs more evidence']];

export default function ReportDetailRoute() {
  const { id } = useParams(); const navigate = useNavigate(); const { token, user } = useAuth();
  const [report, setReport] = useState(() => getReport(id)); const [downloading, setDownloading] = useState(false); const [error, setError] = useState('');
  if (!report) return <AppShell title="Report not found"><div className="bg-white rounded-2xl border p-12 text-center"><p className="font-bold">This report is not available in this browser workspace.</p><button onClick={() => navigate('/reports')} className="mt-4 text-sky-700 font-bold">Back to reports</button></div></AppShell>;
  const save = (patch) => { const next = updateReport(report.id, patch); setReport(next); return next; };
  const download = async () => { setDownloading(true); setError(''); try { const blob = await downloadReportPdf(report, token); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `PackMetrix-${report.id}.pdf`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (failure) { setError(failure.message); } finally { setDownloading(false); } };
  const resolveFinding = (ruleId, patch) => save({ results: report.results.map((item) => item.rule_id === ruleId ? { ...item, ...patch } : item), violations: report.violations.map((item) => item.rule_id === ruleId ? { ...item, ...patch } : item) });
  const finalise = () => { const unresolved = report.results.filter((item) => item.outcome === 'REVIEW' && !item.resolvedOutcome).length; save({ workflowStatus: 'RESOLVED', finalDecision: unresolved ? 'Resolved with additional evidence required' : 'Officer review completed', reviewedBy: { id: user?.id, name: user?.name, email: user?.email }, reviewedAt: new Date().toLocaleString('en-IN') }); };
  const archive = () => { if (!window.confirm(`Archive report ${report.id}? It can be restored from the report register.`)) return; archiveReport(report.id); navigate('/reports'); };
  const action = <div className="flex gap-2"><button onClick={download} disabled={downloading} className="flex items-center gap-2 bg-slate-950 text-white rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-50"><Download className="w-4 h-4" />{downloading ? 'Generating…' : 'Download PDF'}</button></div>;
  const statusLabel = report.workflowStatus === 'RESOLVED' ? 'OFFICER VERIFIED / RESOLVED' : report.status === 'REVIEW' ? 'REVIEW REQUIRED' : report.status === 'NON_COMPLIANT' ? 'NON-COMPLIANT' : 'COMPLIANT';
  const bulkBatch = report.batchId ? getBulkBatch(report.batchId) : null; const failures = (report.results || []).filter((item) => item.outcome === 'FAIL'); const reviews = (report.results || []).filter((item) => item.outcome === 'REVIEW');
  return <AppShell title={`Report ${report.id}`} eyebrow="AI COMPLIANCE ANALYSIS" actions={action}>
    <button onClick={() => navigate(bulkBatch ? `/inspections/new?mode=bulk&batch=${encodeURIComponent(report.batchId)}` : '/reports')} className="flex gap-2 items-center text-sm font-bold text-slate-600 mb-5"><ArrowLeft className="w-4 h-4" />{bulkBatch ? 'Back to bulk results' : 'All reports'}</button>
    {error && <div className="mb-5 bg-rose-50 border border-rose-200 rounded-xl p-4 text-sm text-rose-800">{error}</div>}
    <section className="grid xl:grid-cols-[.7fr_1.3fr] gap-5">
      <div className="space-y-5"><AssessmentCard report={report} statusLabel={statusLabel} failures={failures} reviews={reviews} /><Card title="Submitted evidence" icon={ImageIcon}>{report.thumbnail ? <img src={report.thumbnail} className="w-full rounded-xl max-h-72 object-contain bg-slate-100" alt="Submitted package evidence" /> : <p className="text-sm text-slate-500">Preview not retained.</p>}<p className="mt-4 text-xs text-slate-500">{report.imageCount} package surface(s) · {report.ocrStatus}</p></Card><Card title={`Complete extracted text (${report.ocrLines?.length || 0})`} icon={FileText}>{report.ocrLines?.length ? <div className="max-h-80 overflow-y-auto space-y-2">{report.ocrLines.map((line, index) => <div key={`${line.text}-${index}`} className="grid grid-cols-[28px_1fr_auto] gap-2 text-xs border-b border-slate-100 pb-2"><span className="font-mono text-slate-400">{String(index + 1).padStart(2, '0')}</span><span className="break-words">{line.text}</span><span className="text-emerald-700 font-bold">{Math.round((line.confidence || 0) * 100)}%</span></div>)}</div> : <p className="text-sm text-slate-500">No OCR transcript was retained for this report.</p>}</Card><Card title="Ingredients" icon={FileText}><IngredientList value={report.declarations?.ingredients} /></Card><Card title="Nutrition information" icon={FileText}><NutritionTable value={report.declarations?.nutrition_information} /></Card></div>
      <div className="space-y-5"><Card title="Product and declaration details" icon={FileText}><Info label="Product ID" value={report.details?.productId || report.id} /><Info label="Product name" value={report.details?.productName} />{DETAIL_FIELDS.map(([label, field]) => <Info key={field} label={label} value={report.declarations?.[field]} evidence={report.fieldEvidence?.[field]} />)}</Card>{failures.length > 0 && <StatusSection tone="violation" title={`Violations detected (${failures.length})`} description="Package evidence is complete enough to establish that these declarations are missing or invalid.">{failures.map((item) => <Finding key={item.rule_id} tone="violation" item={item} onChange={(patch) => resolveFinding(item.rule_id, patch)} />)}</StatusSection>}<StatusSection tone="review" title={`Needs officer review (${reviews.length})`} description="Evidence is incomplete, conflicting, or uncertain. These are not confirmed violations.">{reviews.length ? reviews.map((item) => <Finding key={item.rule_id} tone="review" item={item} onChange={(patch) => resolveFinding(item.rule_id, patch)} />) : <p className="flex gap-2 text-sm text-emerald-700"><CheckCircle2 className="w-5 h-5" />No unresolved review findings.</p>}</StatusSection><Card title="Officer resolution" icon={Save}><label className="text-xs font-bold uppercase text-slate-600">Final officer remarks<textarea value={report.officerRemarks || ''} onChange={(e) => save({ officerRemarks: e.target.value })} rows="3" className="mt-2 w-full border border-slate-300 rounded-xl p-3 text-sm normal-case font-normal" placeholder="Record the basis for the final disposition" /></label><div className="flex flex-wrap gap-2 mt-4">{report.workflowStatus !== 'RESOLVED' ? <button onClick={finalise} className="bg-sky-700 text-white rounded-xl px-4 py-2.5 text-sm font-bold">Mark resolved</button> : <button onClick={() => save({ workflowStatus: 'OPEN', finalDecision: 'Reopened for officer review' })} className="flex gap-2 items-center border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold"><RotateCcw className="w-4 h-4" />Reopen</button>}<button onClick={archive} className="flex gap-2 items-center border border-rose-200 text-rose-700 rounded-xl px-4 py-2.5 text-sm font-bold"><Archive className="w-4 h-4" />Archive report</button></div>{report.reviewedAt && <p className="text-xs text-slate-500 mt-4">Last resolved by {report.reviewedBy?.name || 'authorized officer'} on {report.reviewedAt}</p>}</Card></div>
    </section>
  </AppShell>;
}

function Finding({ item, onChange, tone }) { const violation = tone === 'violation'; return <div className={`rounded-xl border-l-4 p-4 ${violation ? 'border border-rose-200 border-l-rose-600 bg-rose-50/60' : 'border border-amber-200 border-l-amber-500 bg-amber-50/50'}`}><div className="flex items-start gap-3">{violation ? <XCircle className="w-5 h-5 text-rose-600 shrink-0" /> : <HelpCircle className="w-5 h-5 text-amber-600 shrink-0" />}<div><span className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-black tracking-wide ${violation ? 'bg-rose-100 text-rose-800' : 'bg-amber-100 text-amber-800'}`}>{item.resolvedOutcome ? 'OFFICER VERIFIED' : violation ? 'VIOLATION' : 'REVIEW REQUIRED'}</span><p className="font-bold text-sm mt-2">{item.requirement}</p></div></div>{item.evidence?.length > 0 && <div className="rounded-lg bg-white/80 border border-slate-200 px-3 py-2 text-xs mt-3"><b>Package evidence:</b> {item.evidence.map((e) => e.value).join('; ')}</div>}<p className="text-sm text-slate-700 mt-3"><b>Why:</b> {item.reason}</p><p className="text-xs text-slate-500 mt-1">{item.rule_reference}</p><div className="flex flex-wrap gap-2 mt-3">{OUTCOMES.map(([value,label]) => <button key={value} onClick={() => onChange({ resolvedOutcome: value })} className={`rounded-lg border px-3 py-1.5 text-xs font-bold ${item.resolvedOutcome === value ? 'bg-sky-50 border-sky-400 text-sky-800' : 'bg-white border-slate-200 text-slate-600'}`}>{label}</button>)}</div><textarea value={item.officerRemark || ''} onChange={(e) => onChange({ officerRemark: e.target.value })} placeholder="Add officer remark" rows="2" className="mt-3 w-full rounded-lg border border-slate-200 p-2.5 text-sm bg-white" /><button onClick={() => onChange({ decisionSavedAt: new Date().toLocaleString('en-IN') })} className="mt-2 text-xs font-bold text-sky-700">Save decision</button>{item.decisionSavedAt && <span className="ml-3 text-xs text-emerald-700">Saved {item.decisionSavedAt}</span>}</div>; }
function AssessmentCard({ report, statusLabel, failures, reviews }) { const score = report.verificationScore ?? report.score ?? 0; return <div className="bg-slate-950 text-white rounded-2xl p-6"><p className="text-xs font-bold text-sky-400 tracking-widest">ASSESSMENT</p><p className="text-3xl font-black mt-3">{statusLabel}</p><div className="grid grid-cols-3 gap-2 mt-5 text-center"><Count value={report.counts?.PASS} label="Passed" tone="pass" /><Count value={report.counts?.FAIL} label="Violations" tone="fail" /><Count value={report.counts?.REVIEW} label="Need review" tone="review" /></div><div className="mt-5 h-2 rounded-full bg-slate-800 overflow-hidden"><div className="h-full rounded-full bg-sky-400" style={{ width: `${Math.max(0, Math.min(100, score))}%` }} /></div><div className="flex justify-between mt-1 text-[10px] text-slate-400"><span>Evidence verified</span><span>{score}%</span></div><p className="text-xs text-slate-200 leading-5 mt-4">{report.overallReason || (failures.length ? 'Complete package evidence establishes one or more missing or invalid declarations.' : reviews.length ? 'No violation is confirmed, but some checks require clearer evidence or an officer decision.' : 'All applicable checks passed.')}</p><div className="grid gap-1.5 mt-4 text-[11px]"><p className="text-rose-300"><b>Violation:</b> sufficient evidence establishes a missing or invalid declaration.</p><p className="text-amber-300"><b>Review:</b> evidence is uncertain or incomplete; this is not a violation.</p></div></div>; }
function StatusSection({ tone, title, description, children }) { const violation = tone === 'violation'; return <section className={`rounded-2xl border p-5 shadow-sm ${violation ? 'border-rose-200 bg-rose-50/30' : 'border-amber-200 bg-amber-50/20'}`}><div className="flex gap-3 items-start">{violation ? <XCircle className="w-5 h-5 text-rose-600" /> : <AlertTriangle className="w-5 h-5 text-amber-600" />}<div><h3 className={`font-black ${violation ? 'text-rose-900' : 'text-amber-900'}`}>{title}</h3><p className="text-xs text-slate-600 mt-1">{description}</p></div></div><div className="mt-4 space-y-4">{children}</div></section>; }
function IngredientList({ value }) { if (!value) return <p className="text-sm text-slate-500">Not reliably detected</p>; const items = value.split(/[,;]+/).map((item) => item.trim()).filter(Boolean); return <div className="flex flex-wrap gap-2">{items.map((item, index) => <span key={`${item}-${index}`} className="rounded-full border border-sky-100 bg-sky-50 px-3 py-1.5 text-xs font-semibold text-slate-700">{item}</span>)}</div>; }
function parseNutrition(value) { if (!value) return []; return value.split(';').map((entry) => entry.trim()).filter(Boolean).map((entry) => { const percent = entry.match(/\d+(?:[.,]\d+)?\s*%/g)?.join(', ') || '—'; const withoutPercent = entry.replace(/\d+(?:[.,]\d+)?\s*%/g, '').trim(); const amountStart = withoutPercent.search(/\d/); if (amountStart < 0) return { nutrient: withoutPercent, amount: '—', percent }; return { nutrient: withoutPercent.slice(0, amountStart).trim().replace(/[:.-]+$/, '') || 'Value', amount: withoutPercent.slice(amountStart).trim(), percent }; }); }
function NutritionTable({ value }) { const rows = parseNutrition(value); if (!rows.length) return <p className="text-sm text-slate-500">Not reliably detected</p>; return <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500 uppercase"><tr><th className="px-3 py-2.5">Nutrient</th><th className="px-3 py-2.5">Declared amount</th><th className="px-3 py-2.5 text-right">% RDA / DV</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => <tr key={`${row.nutrient}-${index}`} className="hover:bg-sky-50/40"><td className="px-3 py-2.5 font-bold text-slate-700">{row.nutrient}</td><td className="px-3 py-2.5 text-slate-700">{row.amount}</td><td className="px-3 py-2.5 text-right font-semibold text-slate-600">{row.percent}</td></tr>)}</tbody></table><p className="border-t border-slate-100 bg-slate-50 px-3 py-2 text-[10px] text-slate-500">Structured for future cross-product comparison; values remain OCR evidence until verified.</p></div>; }
function Card({ title, icon: Icon, children }) { return <section className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><h3 className="font-black flex items-center gap-2"><Icon className="w-4 h-4 text-sky-700" />{title}</h3><div className="mt-4">{children}</div></section>; }
function Count({ value = 0, label, tone }) { const colors = { pass: 'border-emerald-400/40 bg-emerald-400/10 text-emerald-300', fail: 'border-rose-400/50 bg-rose-400/10 text-rose-300', review: 'border-amber-400/50 bg-amber-400/10 text-amber-300' }; return <div className={`rounded-xl border p-3 ${colors[tone]}`}><p className="text-2xl font-black">{value}</p><p className="text-[10px] font-bold uppercase tracking-wide">{label}</p></div>; }
function Info({ label, value, evidence }) { const uncertain = evidence && evidence.confidence < .8; const matchedEvidence = value && evidence?.value === value; return <div className="grid sm:grid-cols-[210px_1fr] gap-1 py-2 border-b border-slate-100 last:border-0"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="text-sm font-semibold break-words">{value || 'Not reliably detected'}{matchedEvidence && <span className={`ml-2 text-[10px] rounded-full px-2 py-0.5 ${uncertain ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'}`}>{uncertain ? 'Review' : 'AI extracted'} {Math.round(evidence.confidence * 100)}%</span>}</p></div>; }
